name: Hello World Workflow

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your repository so the workflow can access it

      - name: Say Hello
        run: echo "Hello, GitHub Actions!" # Executes a simple command to print a message
